/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as PlanesRouteImport } from './routes/planes'
import { Route as PasadiasRouteImport } from './routes/pasadias'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as AlojamientoRouteImport } from './routes/alojamiento'
import { Route as IndexRouteImport } from './routes/index'

const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesRoute = PlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => rootRouteImport,
} as any)
const PasadiasRoute = PasadiasRouteImport.update({
  id: '/pasadias',
  path: '/pasadias',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AlojamientoRoute = AlojamientoRouteImport.update({
  id: '/alojamiento',
  path: '/alojamiento',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alojamiento': typeof AlojamientoRoute
  '/cookies': typeof CookiesRoute
  '/pasadias': typeof PasadiasRoute
  '/planes': typeof PlanesRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/tours': typeof ToursRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alojamiento': typeof AlojamientoRoute
  '/cookies': typeof CookiesRoute
  '/pasadias': typeof PasadiasRoute
  '/planes': typeof PlanesRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/tours': typeof ToursRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alojamiento': typeof AlojamientoRoute
  '/cookies': typeof CookiesRoute
  '/pasadias': typeof PasadiasRoute
  '/planes': typeof PlanesRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/tours': typeof ToursRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alojamiento'
    | '/cookies'
    | '/pasadias'
    | '/planes'
    | '/privacidad'
    | '/terminos'
    | '/tours'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alojamiento'
    | '/cookies'
    | '/pasadias'
    | '/planes'
    | '/privacidad'
    | '/terminos'
    | '/tours'
  id:
    | '__root__'
    | '/'
    | '/alojamiento'
    | '/cookies'
    | '/pasadias'
    | '/planes'
    | '/privacidad'
    | '/terminos'
    | '/tours'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlojamientoRoute: typeof AlojamientoRoute
  CookiesRoute: typeof CookiesRoute
  PasadiasRoute: typeof PasadiasRoute
  PlanesRoute: typeof PlanesRoute
  PrivacidadRoute: typeof PrivacidadRoute
  TerminosRoute: typeof TerminosRoute
  ToursRoute: typeof ToursRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes': {
      id: '/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof PlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pasadias': {
      id: '/pasadias'
      path: '/pasadias'
      fullPath: '/pasadias'
      preLoaderRoute: typeof PasadiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alojamiento': {
      id: '/alojamiento'
      path: '/alojamiento'
      fullPath: '/alojamiento'
      preLoaderRoute: typeof AlojamientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlojamientoRoute: AlojamientoRoute,
  CookiesRoute: CookiesRoute,
  PasadiasRoute: PasadiasRoute,
  PlanesRoute: PlanesRoute,
  PrivacidadRoute: PrivacidadRoute,
  TerminosRoute: TerminosRoute,
  ToursRoute: ToursRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
